/* This file is automatically generated; do not edit.     */
/* Add the files to be included into Makefile.am instead. */


#include <ql/experimental/hullwhitewithtwocurves/model/all.hpp>
#include <ql/experimental/hullwhitewithtwocurves/pricingengines/all.hpp>
